#!/bin/sh

# Launch things {{{

pkill sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

xsetroot -solid '#202020'
xsetroot -cursor_name left_ptr
nitrogen --set-zoom-fill ~/Downloads/jonatan-pie-367745.jpg

pkill compton
compton -b &

killall dunst
dunst -conf ~/.config/dunst/dunstrc &

pkill polybar
polybar -c $HOME/.config/polybar/config top &

pkill rescuetime
rescuetime &

pkill nm-applet
nm-applet &

# Monitors & Desktops {{{

mon_int="LVDS1"
mon_ext="HDMI1"

if xrandr -q | grep -i "HDMI1 Conn"; then
	bspc monitor $mon_int -d term web chat code notes steam
	bspc monitor $mon_ext -d main stream
#	dualmon flip
else
	bspc monitor $mon_int -d term web chat code notes steam
	dualmon none
#	xmodmap .XmodmapOFF
fi

# }}}


bspc monitor -d I II III IV V VI VII VIII

# Formatting {{{

bspc config presel_feedback_color "#2d2d2d"
bspc config border_width        5
bspc config window_gap          0
bspc config top_padding 40
bspc config center_pseudo_tiled 	true
bspc config active_window_opacity 	0.2
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 		true
bspc config focus_follows_pointer false

bspc config focused_border_color \#16c98d
bspc config normal_border_color \#1D2021
 
# }}}


# Rules {{{

bspc rule -a "Steam":Steam desktop='steam'
bspc rule -a Emacs state='fullscreen'
# }}}


